# loj-measure:begin mock-data
rows = [
  FlightAvailabilityReadModelResult(
    flightNo="LJ501",
    routeCode="CTS-HND",
    departureCode="CTS",
    arrivalCode="HND",
    departureAirportName="Sapporo (CTS)",
    arrivalAirportName="Haneda",
    departureTime="10:40",
    arrivalTime="12:15",
    travelDate=input.homewardDate,
    cabin="ECONOMY",
    fareBrand="Saver",
    baseFare=Decimal("118"),
    quotedFare=Decimal("0"),
    seatsRemaining=2,
    availabilityBand="LIMITED",
    baggageSummary="1 checked bag",
    changePolicySummary="Changes with fee",
    ticketingAdvisory="Ticket within 30 minutes",
    vacancyMessage="Only 2 seats left on this return fare",
    fareRulesSummary="Basic changes plus seat-assignment fee",
    boardingSummary="Boarding group C with standard return boarding",
    refundPolicySummary="Refund as credit after the return hold expires",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ501",
    routeCode="CTS-HND",
    departureCode="CTS",
    arrivalCode="HND",
    departureAirportName="Sapporo (CTS)",
    arrivalAirportName="Haneda",
    departureTime="10:40",
    arrivalTime="12:15",
    travelDate=input.homewardDate,
    cabin="ECONOMY",
    fareBrand="Flex",
    baseFare=Decimal("132"),
    quotedFare=Decimal("0"),
    seatsRemaining=4,
    availabilityBand="AVAILABLE",
    baggageSummary="1 checked bag",
    changePolicySummary="Changes allowed",
    ticketingAdvisory="Ticket by end of day",
    vacancyMessage="Good return availability",
    fareRulesSummary="Same-day change permitted once",
    boardingSummary="Boarding group B with early bag-drop for the return",
    refundPolicySummary="Refund to original payment before return ticketing closes",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ501",
    routeCode="CTS-HND",
    departureCode="CTS",
    arrivalCode="HND",
    departureAirportName="Sapporo (CTS)",
    arrivalAirportName="Haneda",
    departureTime="10:40",
    arrivalTime="12:15",
    travelDate=input.homewardDate,
    cabin="ECONOMY",
    fareBrand="Plus",
    baseFare=Decimal("148"),
    quotedFare=Decimal("0"),
    seatsRemaining=4,
    availabilityBand="AVAILABLE",
    baggageSummary="2 checked bags",
    changePolicySummary="Changes allowed",
    ticketingAdvisory="Ticket by end of day",
    vacancyMessage="Extra baggage still available",
    fareRulesSummary="Priority boarding and same-day change",
    boardingSummary="Priority boarding with group-travel lane support",
    refundPolicySummary="Refund as credit with baggage upsell preserved",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ611",
    routeCode="CTS-HND",
    departureCode="CTS",
    arrivalCode="HND",
    departureAirportName="Sapporo (CTS)",
    arrivalAirportName="Haneda",
    departureTime="15:05",
    arrivalTime="16:40",
    travelDate=input.homewardDate,
    cabin="BUSINESS",
    fareBrand="Business Saver",
    baseFare=Decimal("245"),
    quotedFare=Decimal("0"),
    seatsRemaining=1,
    availabilityBand="LIMITED",
    baggageSummary="2 checked bags",
    changePolicySummary="Changes with fee",
    ticketingAdvisory="Agent ticketing only",
    vacancyMessage="Last saver seat in business cabin",
    fareRulesSummary="Lounge access with change fee",
    boardingSummary="Priority lane plus lounge reception handoff",
    refundPolicySummary="Refund review required through the agency desk",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ611",
    routeCode="CTS-HND",
    departureCode="CTS",
    arrivalCode="HND",
    departureAirportName="Sapporo (CTS)",
    arrivalAirportName="Haneda",
    departureTime="15:05",
    arrivalTime="16:40",
    travelDate=input.homewardDate,
    cabin="BUSINESS",
    fareBrand="Business Flex",
    baseFare=Decimal("285"),
    quotedFare=Decimal("0"),
    seatsRemaining=2,
    availabilityBand="LIMITED",
    baggageSummary="2 checked bags",
    changePolicySummary="Changes allowed",
    ticketingAdvisory="Agent ticketing only",
    vacancyMessage="Business flex seats almost sold out",
    fareRulesSummary="Lounge access with flexible changes",
    boardingSummary="Priority lane plus lounge escort at check-in",
    refundPolicySummary="Refund to travel credit after agency review",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ702",
    routeCode="OKA-KIX",
    departureCode="OKA",
    arrivalCode="KIX",
    departureAirportName="Naha",
    arrivalAirportName="Kansai",
    departureTime="13:10",
    arrivalTime="15:45",
    travelDate=input.homewardDate,
    cabin="ECONOMY",
    fareBrand="Saver",
    baseFare=Decimal("150"),
    quotedFare=Decimal("0"),
    seatsRemaining=3,
    availabilityBand="AVAILABLE",
    baggageSummary="1 checked bag",
    changePolicySummary="Changes with fee",
    ticketingAdvisory="Ticket by end of day",
    vacancyMessage="Three seats left on saver fare",
    fareRulesSummary="Discount fare with standard boarding",
    boardingSummary="Boarding group C with standard return boarding lane",
    refundPolicySummary="Refund as credit once the saver return window closes",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ702",
    routeCode="OKA-KIX",
    departureCode="OKA",
    arrivalCode="KIX",
    departureAirportName="Naha",
    arrivalAirportName="Kansai",
    departureTime="13:10",
    arrivalTime="15:45",
    travelDate=input.homewardDate,
    cabin="ECONOMY",
    fareBrand="Flex",
    baseFare=Decimal("165"),
    quotedFare=Decimal("0"),
    seatsRemaining=6,
    availabilityBand="AVAILABLE",
    baggageSummary="1 checked bag",
    changePolicySummary="Changes allowed",
    ticketingAdvisory="Ticket by end of day",
    vacancyMessage="Best choice for larger return groups",
    fareRulesSummary="Flexible fare with standard baggage",
    boardingSummary="Boarding group B for smoother return family boarding",
    refundPolicySummary="Refund to original payment before the homeward closes",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ815",
    routeCode="OKA-KIX",
    departureCode="OKA",
    arrivalCode="KIX",
    departureAirportName="Naha",
    arrivalAirportName="Kansai",
    departureTime="18:30",
    arrivalTime="21:05",
    travelDate=input.homewardDate,
    cabin="BUSINESS",
    fareBrand="Business Saver",
    baseFare=Decimal("325"),
    quotedFare=Decimal("0"),
    seatsRemaining=1,
    availabilityBand="LIMITED",
    baggageSummary="2 checked bags",
    changePolicySummary="Changes with fee",
    ticketingAdvisory="Ticket within 15 minutes",
    vacancyMessage="Last business seat for this return",
    fareRulesSummary="Priority handling with short ticketing window",
    boardingSummary="Priority lane with gate-side recovery support",
    refundPolicySummary="Refund review required because the final return seat is protected",
  ),
]
# loj-measure:end mock-data

# loj-measure:begin business-logic
return [
  row
  for row in rows
  if row.departureCode.upper() == input.arrivalCode.upper()
  and row.arrivalCode.upper() == input.departureCode.upper()
  and (not input.cabin or row.cabin.upper() == input.cabin.upper())
  and row.seatsRemaining >= input.passengerCount
]
# loj-measure:end business-logic
