# loj-measure:begin mock-data
rows = [
  FlightAvailabilityReadModelResult(
    flightNo="LJ100",
    routeCode="HND-CTS",
    departureCode="HND",
    arrivalCode="CTS",
    departureAirportName="Haneda",
    arrivalAirportName="Sapporo (CTS)",
    departureTime="08:15",
    arrivalTime="09:50",
    travelDate=input.outwardDate,
    cabin="ECONOMY",
    fareBrand="Saver",
    baseFare=Decimal("110"),
    quotedFare=Decimal("0"),
    seatsRemaining=2,
    availabilityBand="LIMITED",
    baggageSummary="1 checked bag",
    changePolicySummary="Changes with fee",
    ticketingAdvisory="Ticket within 30 minutes",
    vacancyMessage="Only 2 seats left on this fare",
    fareRulesSummary="Basic changes plus seat-assignment fee",
    boardingSummary="Boarding group C with standard check-in lane",
    refundPolicySummary="Refund as credit after the service-fee window",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ100",
    routeCode="HND-CTS",
    departureCode="HND",
    arrivalCode="CTS",
    departureAirportName="Haneda",
    arrivalAirportName="Sapporo (CTS)",
    departureTime="08:15",
    arrivalTime="09:50",
    travelDate=input.outwardDate,
    cabin="ECONOMY",
    fareBrand="Flex",
    baseFare=Decimal("120"),
    quotedFare=Decimal("0"),
    seatsRemaining=4,
    availabilityBand="AVAILABLE",
    baggageSummary="1 checked bag",
    changePolicySummary="Changes allowed",
    ticketingAdvisory="Ticket by end of day",
    vacancyMessage="Good availability for this departure",
    fareRulesSummary="Same-day change permitted once",
    boardingSummary="Boarding group B with earlier bag-drop cutoff",
    refundPolicySummary="Refund to original payment before ticketing closes",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ100",
    routeCode="HND-CTS",
    departureCode="HND",
    arrivalCode="CTS",
    departureAirportName="Haneda",
    arrivalAirportName="Sapporo (CTS)",
    departureTime="08:15",
    arrivalTime="09:50",
    travelDate=input.outwardDate,
    cabin="ECONOMY",
    fareBrand="Plus",
    baseFare=Decimal("145"),
    quotedFare=Decimal("0"),
    seatsRemaining=4,
    availabilityBand="AVAILABLE",
    baggageSummary="2 checked bags",
    changePolicySummary="Changes allowed",
    ticketingAdvisory="Ticket by end of day",
    vacancyMessage="Good availability with extra baggage",
    fareRulesSummary="Priority boarding and same-day change",
    boardingSummary="Priority boarding with overhead-bin guarantee",
    refundPolicySummary="Refund as credit with baggage upsell kept open",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ210",
    routeCode="HND-CTS",
    departureCode="HND",
    arrivalCode="CTS",
    departureAirportName="Haneda",
    arrivalAirportName="Sapporo (CTS)",
    departureTime="11:40",
    arrivalTime="13:15",
    travelDate=input.outwardDate,
    cabin="BUSINESS",
    fareBrand="Business Saver",
    baseFare=Decimal("240"),
    quotedFare=Decimal("0"),
    seatsRemaining=2,
    availabilityBand="LIMITED",
    baggageSummary="2 checked bags",
    changePolicySummary="Changes with fee",
    ticketingAdvisory="Agent ticketing only",
    vacancyMessage="Business cabin nearly full",
    fareRulesSummary="Lounge access with change fee",
    boardingSummary="Priority lane plus lounge reception handoff",
    refundPolicySummary="Refund review required through the agency desk",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ210",
    routeCode="HND-CTS",
    departureCode="HND",
    arrivalCode="CTS",
    departureAirportName="Haneda",
    arrivalAirportName="Sapporo (CTS)",
    departureTime="11:40",
    arrivalTime="13:15",
    travelDate=input.outwardDate,
    cabin="BUSINESS",
    fareBrand="Business Flex",
    baseFare=Decimal("280"),
    quotedFare=Decimal("0"),
    seatsRemaining=2,
    availabilityBand="LIMITED",
    baggageSummary="2 checked bags",
    changePolicySummary="Changes allowed",
    ticketingAdvisory="Agent ticketing only",
    vacancyMessage="Business flex seats almost sold out",
    fareRulesSummary="Lounge access with flexible changes",
    boardingSummary="Priority lane plus lounge escort at check-in",
    refundPolicySummary="Refund to travel credit after agency review",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ320",
    routeCode="KIX-OKA",
    departureCode="KIX",
    arrivalCode="OKA",
    departureAirportName="Kansai",
    arrivalAirportName="Naha",
    departureTime="09:30",
    arrivalTime="12:05",
    travelDate=input.outwardDate,
    cabin="ECONOMY",
    fareBrand="Saver",
    baseFare=Decimal("140"),
    quotedFare=Decimal("0"),
    seatsRemaining=3,
    availabilityBand="AVAILABLE",
    baggageSummary="1 checked bag",
    changePolicySummary="Changes with fee",
    ticketingAdvisory="Ticket by end of day",
    vacancyMessage="Three seats left on saver fare",
    fareRulesSummary="Discount fare with standard boarding",
    boardingSummary="Boarding group C with standard boarding lane",
    refundPolicySummary="Refund as credit once the saver hold expires",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ320",
    routeCode="KIX-OKA",
    departureCode="KIX",
    arrivalCode="OKA",
    departureAirportName="Kansai",
    arrivalAirportName="Naha",
    departureTime="09:30",
    arrivalTime="12:05",
    travelDate=input.outwardDate,
    cabin="ECONOMY",
    fareBrand="Flex",
    baseFare=Decimal("150"),
    quotedFare=Decimal("0"),
    seatsRemaining=6,
    availabilityBand="AVAILABLE",
    baggageSummary="1 checked bag",
    changePolicySummary="Changes allowed",
    ticketingAdvisory="Ticket by end of day",
    vacancyMessage="Best choice for larger parties",
    fareRulesSummary="Flexible fare with standard baggage",
    boardingSummary="Boarding group B for smoother family boarding",
    refundPolicySummary="Refund to original payment before the outbound closes",
  ),
  FlightAvailabilityReadModelResult(
    flightNo="LJ430",
    routeCode="KIX-OKA",
    departureCode="KIX",
    arrivalCode="OKA",
    departureAirportName="Kansai",
    arrivalAirportName="Naha",
    departureTime="14:20",
    arrivalTime="16:55",
    travelDate=input.outwardDate,
    cabin="BUSINESS",
    fareBrand="Business Saver",
    baseFare=Decimal("310"),
    quotedFare=Decimal("0"),
    seatsRemaining=1,
    availabilityBand="LIMITED",
    baggageSummary="2 checked bags",
    changePolicySummary="Changes with fee",
    ticketingAdvisory="Ticket within 15 minutes",
    vacancyMessage="Last business seat for this departure",
    fareRulesSummary="Priority handling with short ticketing window",
    boardingSummary="Priority lane with gate-side recovery support",
    refundPolicySummary="Refund review required because the final seat is protected",
  ),
]
# loj-measure:end mock-data

# loj-measure:begin business-logic
return [
  row
  for row in rows
  if row.departureCode.upper() == input.departureCode.upper()
  and row.arrivalCode.upper() == input.arrivalCode.upper()
  and (not input.cabin or row.cabin.upper() == input.cabin.upper())
  and row.seatsRemaining >= input.passengerCount
]
# loj-measure:end business-logic
